export const {
	SPARKUI_CORE_BASE_URL = 'http://127.0.0.1:1911',
	SPARKUI_CORE_HOST = '127.0.0.1',
	SPARKUI_CORE_DATA_DIR = '/data',
	SPARKUI_CORE_DB_HOST = 'db',
	SPARKUI_CORE_DB_NAME = 'sparkui',
	SPARKUI_CORE_DB_USER = 'postgres',
	SPARKUI_CORE_DB_PASS = 'adminadmin',
	SPARKUI_CORE_JWT_SECRET = 'SECRET',
	SPARKUI_CORE_JWT_EXPIRES = '15m',
	SPARKUI_CORE_JWT_REFRESH_SECRET = 'REFRESH_SECRET',
	SPARKUI_CORE_JWT_REFRESH_EXPIRES = '7d',
	SPARKUI_CORE_CIVITAI_KEY = 'civitai_key',
	SPARKUI_CORE_CIVITAI_BASE = 'https://civitai.com/api/',
} = process.env

export const SPARKUI_CORE_PORT = Number(process.env.SPARKUI_CORE_PORT ?? '1911')
export const SPARKUI_CORE_DB_PORT = Number(process.env.SPARKUI_CORE_DB_PORT ?? '5432')
export const SPARKUI_CORE_DB_SSL = process.env.SPARKUI_CORE_DB_SSL === 'true'
export const SPARKUI_CORE_DB_URL = `postgres://${SPARKUI_CORE_DB_USER}:${SPARKUI_CORE_DB_PASS}@${SPARKUI_CORE_DB_HOST}:${SPARKUI_CORE_DB_PORT}/${SPARKUI_CORE_DB_NAME}`
export const SPARKUI_CORE_MAX_CONCURRENT_DOWNLOADS = Number(process.env.SPARKUI_CORE_MAX_CONCURRENT_DOWNLOADS ?? '5')

export const SPARKUI_CORE_DEBUG = process.env.SPARKUI_CORE_DEBUG === 'true'

process.env.SPARKUI_CORE_DB_URL = SPARKUI_CORE_DB_URL
